[package]
name = "lumi-local-playback"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
lumi-deck-source = { path = "../lumi-deck-source" }
lumi-domain = { path = "../lumi-domain" }
thiserror = "2.0.18"

[lints]
workspace = true
