[package]
name = "lumi-rekordbox-resolver"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
miniz_oxide = "0.8"
sha2 = "0.10.9"
thiserror = "2"

[dev-dependencies]
lumi-rekordbox-analysis = { path = "../lumi-rekordbox-analysis" }
lumi-rekordbox-xml = { path = "../lumi-rekordbox-xml" }

[lints]
workspace = true
