[package]
name = "lumi-midi-coremidi"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
lumi-midi-output = { path = "../lumi-midi-output" }
thiserror = "2"

[target.'cfg(target_os = "macos")'.dependencies]
coremidi = { package = "coremidi-rs", version = "0.5.4" }

[lints]
workspace = true
